const bands = { 

    rock:[  
            'Muse',
            'The Killers', 
            'Arctic Monkeys', 
            //'Joy Division', 
            //'The Script',
            //'The Strokes',
            'Radiohead',
            //'Arcade Fire',
            //'The Smiths',
            //'Cage the Elephant',
            //'Franz Ferdinand',
            //'The Black Keys',
            //'Foster the People',
            //'Interpol',
            //'Imagine Dragons',
            'Oasis',
            //'Kings of Leon',
            //'Snow Patrol',
            //'Placebo',

            //'The Beatles',
            //'Led Zeppelin',
            //'Queen',
            //'Pink Floyd',
            //'The Rolling Stones',
            //'AC/DC',
            //'Eagles',
            'Metallica',
            //"Guns N' Roses",
            //'Aerosmith',
            'Linkin Park',
            'Red Hot Chili Peppers',
            //'Bon Jovi',
            //'U2',
            'Nirvana',
            //'The Who',
            'Green Day',
            //'Pearl Jam',
            //'Nickelback',
            //'Foo Fighters',
            //'Fall Out Boy',
            //'The Police',
            //'ABBA',
            //'Kiss',
            //'R.E.M',
            //'Panic! at the Disco',
            //'Blink-182',
            //'Paramore',
            //'The Cranberries',
            //'Iron Maiden',
            //'The Smashing Pumpkins',
            //'System of a Down',
            //'Slipknot',
            'Three Days Grace',
            //'Evanescence',
            'Avenged Sevenfold'
    ], 

    pop: [  
            'Ariana Grande', 
            'Billie Eilish', 
            'Coldplay',
            'Lana Del Rey',
            //'Maroon 5',
            //'Rihanna',
            //'Katy Perry',
            //'Justin Timberlake',
            //'Britney Spears',
            //'Taylor Swift',
            //'Kelly Clarkson',
            //'Mariah Carey',
            'Bruno Mars',
            //'Usher',
            //'Lady Gaga',
            //'The Black Eyed Peas',
            //'Christina Aguilera',
            //'Madonna',
            //'Beyonce',
            //'Avril Lavigne',
            'Justin Bieber',
            //'Backstreet Boys',
            //'Pitbull',
            //'Selena Gomez',
            //'Demi Lovato',
            //'Adele',
            'Ed Sheeran',
            'Shawn Mendes',
            //'Halsey',
            'The Weeknd',
            'Twenty One Pilots',
            //'One Direction',
            'Charlie Puth',
            //'Sam Smith',
            'LSD'
    ],

    rap: [  
            'Eminem',
            'Kendrick Lamar',
            'Kanye West',
            //'Jay-Z',
            //'Drake',
            'Lil Wayne',
            'Snoop Dogg',
            //'50 Cent',
            //'Ice Cube',
            //'Dr. Dre',
            //'Future',
            'Nicki Minaj',
            'Cardi B',
            //'2Pac',
            //'Tyler, The Creator'
    ]

    //electronic: [
    //        'Marshmello',
    //        'The Chainsmokers',
    //        'Avicii',
    //        'David Guetta',
    //        'Daft Punk',
    //        'Gorillaz',
    //        'Alesso',
    //        //'Tiesto',
    //        'Diplo',
    //        "Gigi D'Agostino",
    //        //'Deadmau5',
    //        'Skrillex'            
    //]
}

export default bands;